# Generated by Django 4.2.4 on 2023-09-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="state",
            field=models.CharField(
                choices=[
                    ("BUSINESS", "Business"),
                    ("IDEA", "Idea"),
                    ("IMAGE", "Image"),
                    ("CAPTION", "Caption"),
                ],
                default="BUSINESS",
                max_length=15,
            ),
        ),
    ]
