# Generated by Django 4.2.4 on 2023-09-14 03:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_chatsession_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatsession",
            name="decision_tree_state",
        ),
    ]
