# Generated by Django 4.2.4 on 2023-09-24 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0003_remove_chatsession_decision_tree_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatsession",
            old_name="user_profile",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="idea",
            old_name="text",
            new_name="idea",
        ),
        migrations.RemoveField(
            model_name="chatlog",
            name="related_caption",
        ),
        migrations.RemoveField(
            model_name="chatlog",
            name="related_idea",
        ),
        migrations.RemoveField(
            model_name="chatlog",
            name="related_image",
        ),
        migrations.AddField(
            model_name="caption",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="session_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="idea",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="image",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="image",
            name="image_prompt",
            field=models.TextField(default="default"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chatlog",
            name="message_type",
            field=models.CharField(
                choices=[("USER", "User"), ("AI", "AI")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="state",
            field=models.CharField(
                choices=[
                    ("BUSINESS", "Business"),
                    ("CHANGE_BUSINESS", "Change_Business"),
                    ("IDEA", "Idea"),
                    ("CHANGE_IDEA", "Change_Idea"),
                    ("IMAGE", "Image"),
                    ("CHANGE_IMAGE", "Change_Image"),
                    ("CAPTION", "Caption"),
                    ("CHANGE_CAPTION", "Change_Caption"),
                    ("FINAL", "Final"),
                ],
                default="BUSINESS",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="UserPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "caption",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat.caption",
                    ),
                ),
                (
                    "idea",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat.idea",
                    ),
                ),
                (
                    "image",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat.image",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusinessDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.TextField(blank=True, null=True)),
                ("business_description", models.TextField(blank=True, null=True)),
                ("target_audience", models.TextField(blank=True, null=True)),
                ("writing_style", models.TextField(blank=True, null=True)),
                ("image_style", models.TextField(blank=True, null=True)),
                (
                    "chat_session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_details",
                        to="chat.chatsession",
                    ),
                ),
            ],
        ),
    ]
